# Generated by Django 4.0 on 2021-12-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_number', models.CharField(max_length=10)),
                ('modem_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('Operator', models.CharField(max_length=60)),
                ('data_time', models.CharField(max_length=100)),
            ],
        ),
    ]
