# Generated by Django 4.0 on 2021-12-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apidata',
            old_name='Operator',
            new_name='operator',
        ),
    ]
