# Generated by Django 4.0 on 2021-12-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_bot', '0002_rename_operator_apidata_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
