# Generated by Django 4.0 on 2021-12-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_bot', '0005_alter_apidata_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
